# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: snmp_notifier
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - dragonfly_amd64
#      - freebsd_386
      - freebsd_amd64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - linux_mips64
      - linux_mips64le
      - netbsd_386
      - netbsd_amd64
      - netbsd_arm
#      - windows_386
      - windows_amd64
    #        - openbsd/amd64
    #        - openbsd/386
    #        - linux/ppc64
    #        - linux/ppc64le
    binary: snmp_notifier
    main: snmp_notifier.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -a
#      - -tags netgo
    ldflags:
      - -s
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      # - -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
      - -X github.com/prometheus/common/version.BuildDate={{time "20060102-15:04:05"}}
archives:
  - id: my-archive
    files:
    - description-template.tpl
    - LICENSE
    - NOTICE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  disable: true